fix: PTS diverge DTS when DTS close to 2pow33 and PTS more than 0
shaka-project/shaka-packager pull request #1050
Opened 2022-03-17 16:07 UTC by zdanek

Fixes #1049

2022-10-27 20:57 UTC, joeyparrish requested changes
Looks good otherwise.  I'll make a quick correction to the test comment and merge it.

2022-10-27 20:57 UTC, joeyparrish commented on packager/media/formats/mp2t/mp2t_media_parser_unittest.cc
> +  // "bear-640x360.ts" has been transcoded from bear-640x360.mp4 by applying a
It appears you quote the wrong file name.  This should be "bear-640x360_ptszero_dtswraparound.ts".

2022-10-27 21:01 UTC, joeyparrish approved these changes

2022-10-27 21:21 UTC, merged

2022-10-28 09:59 UTC, zdanek commented
Thank you.