Cocallaghan/writing colr atom
shaka-project/shaka-packager pull request #1251
Opened 2023-07-27 15:55 UTC by CaitlinOCallaghan

This PR is an extension of the full AV1 codec string feature: [PR 1205](https://github.com/shaka-project/shaka-packager/pull/1205) and relates to [Issue 1007](https://github.com/shaka-project/shaka-packager/issues/1007) and [Issue 1202](https://github.com/shaka-project/shaka-packager/issues/1202). 

As per the AV1 spec, the codec string may contain optional color values. These color values are critical for detecting HDR video streams - see [Issue 1007](https://github.com/shaka-project/shaka-packager/issues/1007). Color information is extracted from the input mp4's `colr` atom and used to generate the full AV1 codec string. This PR preserves the color information by writing the `colr` atom to the muxed mp4.

**References**:
- [AV1 Codec ISO Media File Format Binding](https://aomediacodec.github.io/av1-isobmff/#codecsparam)
- [AV1 Bitstream & Decoding Process
Specification - Section 6.4.2 Color config semantics (page 117)](https://aomediacodec.github.io/av1-spec/av1-spec.pdf)
- [QuickTime File Format Specification](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-125526)

# Testing
## Manual: AV1 video WITH colr atom
Note: Presence of the colr atom in `bbbhdr_av1.mp4` was verified with a hex editor.
![image](https://github.com/CaitlinOCallaghan/shaka-packager/assets/38890251/5780d961-4599-435f-866f-c30d31df9c83)
 
1. Generate Packager MPD with: `./out/Release/packager in=~/Downloads/bbbhdr_av1.mp4,stream=video,output=av1_with_colr.mp4 --mpd_output av1_with_colr.mpd`
2.  Check manifest generated by Shaka Packager for Representation codecs string:
```
<?xml version="1.0" encoding="UTF-8"?>

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT1.100000023841858S">
  <Period id="0">
    <AdaptationSet id="0" contentType="video" width="640" height="360" frameRate="15360/512" subsegmentAlignment="true" par="16:9">
      <Representation id="0" bandwidth="778146" codecs="av01.1.01M.10.0.000.09.16.09.0" mimeType="video/mp4" sar="1:1">
        <BaseURL>av1_with_colr.mp4</BaseURL>
        <SegmentBase indexRange="808-851" timescale="15360">
          <Initialization range="0-807"/>
        </SegmentBase>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```
3.  Check `av1_with_colr.mp4` bitstream for the `colr` atom and cross reference the values of the atom's properties with the codec representation string found in the manifest:
![image](https://github.com/CaitlinOCallaghan/shaka-packager/assets/38890251/f5eb0c77-b601-42cc-accb-829aa0d66f61)

## Format
`git clang-format --style Chromium --binary /usr/bin/clang-format 80e024013df87a4bfeb265c8ea83cfa2a0c5db0f`

2023-08-02 20:02 UTC, joeyparrish approved these changes

2023-08-02 23:57 UTC, CaitlinOCallaghan commented on packager/media/codecs/av1_codec_configuration_record.cc
> +  return base::StringPrintf(
The link is included above on line 76 - I think the PR review port cut it off: 
<img width="712" alt="image" src="https://github.com/shaka-project/shaka-packager/assets/38890251/38249c0a-60a5-419d-9aca-c2e50aaebd36">

2023-08-04 16:59 UTC, cosmin commented
Now that #1205 this needs to be rebased

2023-08-04 17:31 UTC, CaitlinOCallaghan commented
Rebased! :) @cosmin

2023-08-05 03:46 UTC, cosmin approved these changes

2023-08-05 05:19 UTC, cosmin requested changes

2023-08-05 05:19 UTC, cosmin commented on packager/media/formats/mp4/mp4_muxer.cc
> +    auto av1_color_info =
having to parse these back out of the codec string doesn't feel like the right solution

2023-08-29 23:19 UTC, closed without merging

2023-08-29 23:19 UTC, CaitlinOCallaghan commented
Re-published as [PR#1261](https://github.com/shaka-project/shaka-packager/pull/1261), with an improved and more stable implementation.