feat: port media/formats/* to cmake
shaka-project/shaka-packager pull request #1258
Opened 2023-08-22 19:20 UTC by cosmin

2023-08-30 21:36 UTC, joeyparrish requested changes
Finally reviewed.  Sorry it took so long to make time for this!

2023-08-30 21:36 UTC, joeyparrish commented on packager/utils/absl_flag_hexbytes.cc
> +// Created by Cosmin Stejerean on 7/18/23.
Please fix this to a copyright header consistent with the rest of the project.

2023-08-31 17:30 UTC, cosmin commented on packager/media/formats/wvm/wvm_media_parser.cc
> +uint32_t ntohlFromBuffer(const void* buffer) {
It should be used below in several places but I'll update these callsites to use Load32

2023-08-31 18:52 UTC, cosmin commented on packager/media/base/muxer.h
> +  void set_clock(Clock* clock) { clock_ = clock; }
Updated to use unique_ptr internally and keep passing in a raw pointer and reset to it for now. The caller of this method is going to be in the next pull request (in app). We can potentially change the calling code at that point to directly pass in a unique_ptr and use std::move.

2023-08-31 19:27 UTC, joeyparrish approved these changes

2023-08-31 23:59 UTC, merged