upgrade to alpine 3.19
shaka-project/shaka-packager pull request #1327
Opened 2024-01-04 21:50 UTC by misiek08

We wanted to use newest ffmpeg. Without switching to ubuntu static builds are not properly resolving DNS (glibc vs musl), so the easiest way is to upgrade alpine.

On 3.19 I get
```
#0 13.16 In file included from /shaka-packager/packager/third_party/abseil-cpp/source/absl/base/internal/low_level_alloc.cc:26:
#0 13.16 /shaka-packager/packager/third_party/abseil-cpp/source/absl/base/internal/direct_mmap.h:75:25: error: 'off64_t' has not been declared
#0 13.16    75 |                         off64_t offset) noexcept {
#0 13.16       |                         ^~~~~~~
```
so the easiest is to define alias for macro :)

2024-01-04 21:53 UTC, misiek08 commented
Not sure if `feat` or `chore`

2024-02-08 17:52 UTC, joeyparrish requested changes

2024-02-08 17:52 UTC, joeyparrish commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Doff64_t=off_t")
I don't think this is universally true on all platforms.  We shouldn't assume off_t is 64-bits, even if it's true in your case.

2024-02-08 20:54 UTC, joeyparrish commented
Please merge with `main`, which has changed a lot in the recent `cmake` port.  Thanks!

2024-02-09 19:29 UTC, joeyparrish commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Doff64_t=off_t")
It appears that the use of the non-standard off64_t in absl was fixed upstream in https://github.com/abseil/abseil-cpp/commit/4500c2fada4e952037c59bd65e8be1ba0b29f21e .  Upgrading absl should resolve this.  Testing now.

2024-02-10 03:16 UTC, joeyparrish commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Doff64_t=off_t")
Resolved by #1338 and #1337

2024-02-10 16:24 UTC, cosmin approved these changes

2024-02-10 17:23 UTC, joeyparrish approved these changes

2024-02-10 17:25 UTC, merged