feat: add startwithSAP/subsegmentstartswithSAP for audio tracks
shaka-project/shaka-packager pull request #1346
Opened 2024-02-16 06:19 UTC by cosmin

Replaces #1055

This pull request adds startwithSAP/subsegmentstartswithSAP for aac, ac3, ec3 and ac4 audio tracks according to LIVE or VOD profile.

2024-02-21 16:29 UTC, cosmin commented
Puzzled by how that test is failing only on Windows release static.

2024-02-23 20:45 UTC, joeyparrish commented
> Puzzled by how that test is failing only on Windows release static.

I see an "actual" MPD containing: `<!--Generated with https://github.com/shaka-project/shaka-packager version 00fc734-release-->`, but that line is missing from "expected".

Perhaps the mechanism for stripping that is failing on a particular build.

2024-02-23 20:52 UTC, joeyparrish requested changes
Still looking into the mystery test failure.

2024-02-23 20:52 UTC, joeyparrish commented on packager/mpd/base/adaptation_set.cc
> +  if (subsegment_start_with_sap_ == 1) {
Why store a uint8_t, then only use it if it's 1?  Other values are defined in the spec, such as 2.  Could this maybe set the integer attribute with any non-zero value?

2024-02-23 20:59 UTC, joeyparrish commented
I'm going to test this theory about the failed test by running individual suites in separate invocations using a filter on the command-line.  If I'm right, I should be able to trigger a failure on any platform and build config using a filter.  This can also help hunt down other missing calls to SetPackagerVersionForTesting().

2024-02-23 21:29 UTC, joeyparrish commented
I was wrong.  First, I overlooked this line: `xml_compare.cc:128] Attributes of element AdaptationSet do not match.`

Second, xml_compare.cc seems not to care about comments or about the order of attributes.

The actual difference is:

```
Expected:

...
<AdaptationSet contentType="video" maxWidth="720" maxHeight="480" maxFrameRate="10/1" id="0">
...

Actual:

...
<AdaptationSet contentType="video" maxWidth="720" maxHeight="480" subsegmentStartsWithSAP="1" maxFrameRate="10/1" id="0">
...
```

That was very hard to spot, but actual has `subsegmentStartsWithSAP="1"`, and expected does not.

2024-02-23 21:31 UTC, joeyparrish commented
One of the failing tests is `OnDemandMpdBuilderTest.TwoVideosWithDifferentResolutions`, which compares output against `kFileNameExpectedMpdOutputVideo1And2` which is `video_media_info1and2_expected_mpd_output.txt`.  That file does not mention `subsegmentStartsWithSAP`... so how is the test passing?

I'll look into xml_compare more deeply.

2024-02-23 21:35 UTC, joeyparrish commented
I added some logs to the comparison and just ran the one test on Linux.  When it passes, I see that the actual MPD is missing `subsegmentStartsWithSAP`:

`<AdaptationSet contentType="video" maxWidth="720" maxHeight="480" maxFrameRate="10/1" id="0">`

This leads me to think we have an uninitialized value involved.

2024-02-23 21:37 UTC, joeyparrish commented
`packager/mpd/base/adaptation_set.h` doesn't initialize the new fields you added.  In a release build, where memory is generally not sanitized for you on allocation, they happen to have a starting value that is non-zero.

2024-02-23 21:41 UTC, joeyparrish commented
The test should be fixed now.

2024-02-23 21:42 UTC, joeyparrish approved these changes

2024-02-23 21:43 UTC, joeyparrish commented on packager/mpd/base/adaptation_set.cc
> +  if (subsegment_start_with_sap_ == 1) {
I made this change and updated the PR, and then approved it.  If you agree with the change, feel free to merge.  Otherwise, you can undo this part.

2024-02-23 23:45 UTC, merged