use second sample
shaka-project/shaka-packager pull request #838
Opened 2020-09-09 00:34 UTC by koln67

Use the second sample in mp4 and webm formats. #835 had issues with merging due to golden file conflicts. Because we cannot make dependent pull requests, this is a replica of #835.

2020-09-11 22:42 UTC, koln67 commented on packager/media/formats/webm/segmenter.h
> +  uint32_t sample_durations_[2] = {0u, 0u};
Changed
It seems like OnSampleDurationReady takes uint32_t as an input parameter, but the conversion from int64_t to uint32_t shouldn't be an issue.

2020-09-11 22:42 UTC, koln67 commented on packager/media/formats/mp4/segmenter.cc
> +  if (num_samples_ < 2) {
Added to mp4/segmenter.cc, webm/segmenter.cc, and mp2t/ts_muxer.cc

2024-02-28 22:05 UTC, joeyparrish requested changes

2024-02-28 22:05 UTC, joeyparrish commented on packager/media/formats/mp4/segmenter.h
> +  int32_t sample_durations_[2] = {0, 0};
These are set from `sample.duration()`, which is `int64_t`.

Also, can you please add this same initializer to to sample_durations_ in ts_muxer.h?

2024-02-28 23:52 UTC, joeyparrish approved these changes

2024-02-28 23:53 UTC, merged